#!/bin/sh
# Installs iterm-vibe-board for the current user, from this clone:
#
#   ~/.iterm-vibe-board/bin/vibeboard              launcher for the CLI (hooks and agents call it)
#   ~/.claude/skills/vibeboard                  -> adapters/claude-code/skills/vibeboard
#   ~/.claude/settings.json                        SessionStart and SessionEnd hooks added
#   ~/Library/Application Support/iTerm2/Scripts/AutoLaunch/vibeboard_panel.py -> iterm/vibeboard_panel.py
#
# Rerun after `git pull`. `install.sh --uninstall` removes all of it; the data stays.
set -eu

ROOT=$(cd "$(dirname "$0")" && pwd -P)
DATA=${VIBEBOARD_HOME:-$HOME/.iterm-vibe-board}
BIN=$DATA/bin/vibeboard
SKILL=$HOME/.claude/skills/vibeboard
SETTINGS=$HOME/.claude/settings.json
AUTOLAUNCH="$HOME/Library/Application Support/iTerm2/Scripts/AutoLaunch"
PANEL=$AUTOLAUNCH/vibeboard_panel.py
PYTHON=$(command -v python3 || true)

hooks() { # install | uninstall: keep every other hook in place, touch only ours
  "$PYTHON" - "$1" "$SETTINGS" "$BIN hook" <<'EOF'
import json, os, sys

mode, path, command = sys.argv[1:]
try:
    with open(path, encoding="utf-8") as f:
        settings = json.load(f)
except (OSError, ValueError):
    settings = {}
hooks = settings.setdefault("hooks", {})
for event in ("SessionStart", "SessionEnd"):
    ours = lambda g: any(h.get("command", "").endswith("/vibeboard hook") for h in g.get("hooks", []))
    groups = [g for g in hooks.get(event, []) if not ours(g)]
    if mode == "install":
        groups.append({"hooks": [{"type": "command", "command": command}]})
    if groups:
        hooks[event] = groups
    else:
        hooks.pop(event, None)
if not hooks:
    settings.pop("hooks", None)
os.makedirs(os.path.dirname(path), exist_ok=True)
tmp = path + ".tmp"
with open(tmp, "w", encoding="utf-8") as f:
    json.dump(settings, f, indent=2, ensure_ascii=False)
    f.write("\n")
os.replace(tmp, path)
EOF
}

runtime_python() { # iTerm2's own Python runtime, which runs AutoLaunch scripts
  # 3.7 installs it with uv under ~/.config/iterm2; older versions under Application Support.
  ls -d "$HOME/.config/iterm2/AppSupport/uv/venvs/"*/bin/python3 \
        "$HOME/Library/Application Support/iTerm2/iterm2env/versions/"*/bin/python3 2>/dev/null | tail -1
}

uninstall() {
  pkill -f "$PANEL" 2>/dev/null || true
  pkill -f "vibeboard serve" 2>/dev/null || true
  rm -f "$BIN" "$SKILL" "$PANEL"
  [ -f "$SETTINGS" ] && hooks uninstall
  echo "Removed the launcher, the skill, the hooks and the AutoLaunch script."
  echo "Your items are still in $DATA; delete that directory if you want them gone too."
}

install() {
  [ -n "$PYTHON" ] || { echo "python3 not found; run: xcode-select --install" >&2; exit 1; }

  mkdir -p "$DATA/bin" "$HOME/.claude/skills" "$AUTOLAUNCH"
  cat > "$BIN" <<EOF
#!/bin/sh
# generated by $ROOT/install.sh
PYTHONPATH="$ROOT\${PYTHONPATH:+:\$PYTHONPATH}" exec "$PYTHON" -m vibeboard "\$@"
EOF
  chmod +x "$BIN"
  ln -sfn "$ROOT/adapters/claude-code/skills/vibeboard" "$SKILL"
  hooks install
  ln -sfn "$ROOT/iterm/vibeboard_panel.py" "$PANEL"
  echo "Installed:"
  echo "  $BIN"
  echo "  $SKILL"
  echo "  $SETTINGS  (SessionStart, SessionEnd)"
  echo "  $PANEL"

  if ! command -v vibeboard >/dev/null 2>&1; then
    line="export PATH=\"$DATA/bin:\$PATH\""
    if grep -qF "$DATA/bin" "$HOME/.zshrc" 2>/dev/null; then
      echo "~/.zshrc already puts $DATA/bin on PATH; open a new shell for \`vibeboard\` to work."
    elif [ "$(basename "${SHELL:-}")" = zsh ]; then
      printf '\n# iterm-vibe-board\n%s\n' "$line" >> "$HOME/.zshrc"
      echo "Added $DATA/bin to PATH in ~/.zshrc; open a new shell for \`vibeboard\` to work."
    else
      echo "Put \`vibeboard\` on your PATH: $line"
    fi
  fi

  runtime=$(runtime_python)
  if [ -z "$runtime" ]; then
    echo "iTerm2's Python runtime is missing, so the panel cannot start yet:"
    echo "  Scripts › Manage › Install Python Runtime, then restart iTerm2 (or rerun install.sh)."
  elif pgrep -qf "vibeboard_panel.py"; then
    echo "The panel is already running."
  else
    nohup "$runtime" "$PANEL" >/dev/null 2>&1 &
    echo "Panel started; enable it under View › Toolbelt › Vibe Board. iTerm2 starts it itself from now on."
  fi
}

case "${1:-}" in
  "") install ;;
  --uninstall) uninstall ;;
  *) echo "usage: install.sh [--uninstall]" >&2; exit 2 ;;
esac
